image: docker:latest
services:
  - docker:dind

stages:
  - build

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA
  IMAGE_LATEST_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:latest

build:
  stage: build
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} --password-stdin
  script:
    - docker build . -t $IMAGE_TAG  -f  Dockerfile
    - docker tag $IMAGE_TAG $IMAGE_LATEST_TAG
    - docker push $IMAGE_TAG
    - docker push $IMAGE_LATEST_TAG
  only:
    - dev
