image: docker:latest
services:
  - docker:dind

stages:
  - build

build:
  stage: build
  before_script:
    - export VERSION=$(date --utc '+%Y-%m-%d-%H-%M')
    - echo "$CI_REGISTRY_PASSWORD" | docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} --password-stdin
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$VERSION .
    - docker push $CI_REGISTRY_IMAGE:$VERSION
  only:
    - dev
