version: "3.4"

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      DB_HOST: "%"
      DB_NAME: Hokolity
      DB_USER: root
      DB_PASSWORD: HOKOLITY12345678
      MYSQL_ROOT_PASSWORD: HOKOLITY12345678
    ports:
      - 3306:3306
    volumes:
      - ./Services_Data/lotery/postgres:/var/lib/postgresql/data/
    expose:
      - 3306
  soketi:
    image: quay.io/soketi/soketi:0.34-16-debian
    restart: always
    environment:
      DEFAULT_APP_ID: "1419288"
      DEFAULT_APP_KEY: "25ffc95438e35357c167"
      DEFAULT_APP_SECRET: "07c6ed0a7df866a0feb2"
      DEFAULT_APP_MAX_CONNS: 20
      DEFAULT_APP_ENABLE_CLIENT_MESSAGES: true
    ports:
      - 6001:6001
    expose:
      - 6001
  hokodity:
    depends_on:
      - mysqldb
    image: backend
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    expose:
      - 3001
