version: "3.4"

volumes:
  data:

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpw
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - data:/data/redis

  soketi:
    image: quay.io/soketi/soketi:0.34-16-debian
    environment:
      DEFAULT_APP_ID: "1419288"
      DEFAULT_APP_KEY: "25ffc95438e35357c167"
      DEFAULT_APP_SECRET: "07c6ed0a7df866a0feb2"
      DEFAULT_APP_MAX_CONNS: 20
      DEFAULT_APP_ENABLE_CLIENT_MESSAGES: 1
    ports:
      - "6001:6001"
    expose:
      - 6001
    restart: always
    volumes:
      - data:/data/soketi

  hokodity:
    depends_on:
      - mysql
    image: hokobackend
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: mysqlpw
      DB_NAME: hokodity
      JWT_SIGN_SECRET: "secret"
    ports:
      - "3001:3001"
    expose:
      - 3001
