version: "3.4"

services:
  db:
    image: postgres:latest
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hokodity
      POSTGRES_DB: hokodity
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db:/data/postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - db:/data/redis
